### ISSUE TITLE
Ensure that preferences file is stored in ~/Library/Akso on Mac (explicitly specify path)

### ISSUE THREAD

**Issue by zrnsm** [zrna-research/akso#1]
https://github.com/zrna-research/akso/blob/2937859ea6c3e89f51bce7d431537875796e5ee8/axoloti/src/main/java/axoloti/preferences/Preferences.java#L279

The prefs file is just assumed to be in the current working directory of the application. This is just fine on Windows and Linux. The file gets stored in the installation directory.

On Mac, this is actually inside the `.app` which is not normally writable.

Right now we detect MacOS and write the library files to `~/Library/Akso`. The prefs file needs to be written there as well. We should be able to follow the same exact pattern.

**Comment by zrna-research** [comment]
Fixed in 3.0.2-dev.
