### ISSUE TITLE
Windows: zip-file complains about duplicate file due to case-insentivity

### ISSUE THREAD

**Issue by ivogrig** [zrna-research/akso#10]
![extract](https://user-images.githubusercontent.com/10848442/96165029-5edd6280-0f1c-11eb-8289-3734afe08941.png)

You get this when extracting the current release's zip file.
Not sure what can be done about that, it's the same file-name and windows (I will usually run on linux).
Just wanted it to be documented. I am "ivofx" in the forums by the way :)

**Comment by zrnsm** [comment]
Such an annoying problem! I'm normally doing development from Linux as well. Same issue over here too: https://github.com/zrna-research/akso/issues/2

**Comment by ivogrig** [comment]
Oh it's a duplicate then, so I will close it
